In [1]:
aList = ["John", 33, "Toronto", True]
print(aList)

['John', 33, 'Toronto', True]


In [2]:
Mahasiswa = ["Rifqi Muhammad", 2020071014,"INF", "DAA", "15/9/2021","UPJ"]
print(Mahasiswa)

['Rifqi Muhammad', 2020071014, 'INF', 'DAA', '15/9/2021', 'UPJ']


In [3]:
bin_color= ['Red','Green','Blue','Yellow']
bin_color[1]

'Green'

In [4]:
Mahasiswa[1]

2020071014

In [5]:
Mahasiswa[5]

'UPJ'

In [6]:
bin_color[0:4]

['Red', 'Green', 'Blue', 'Yellow']

In [7]:
Mahasiswa[0:6]

['Rifqi Muhammad', 2020071014, 'INF', 'DAA', '15/9/2021', 'UPJ']

In [8]:
bin_color1= ['Red','Green','Blue','Yellow']
for aColor in bin_color1:
    print( aColor + "Square" )

RedSquare
GreenSquare
BlueSquare
YellowSquare


In [10]:
Mahasiswa1 = ["Rifqi", "Salwa", "Rehan", "Wilskuy"]
for aMahasiswa in Mahasiswa1:
    print("UPJ."+ aMahasiswa )

UPJ.Rifqi
UPJ.Salwa
UPJ.Rehan
UPJ.Wilskuy


In [11]:
bin_colors = ('White','Green','Blue','Yellow')
bin_colors [1]

'Green'

In [12]:
bin_colors[2:]

('Blue', 'Yellow')

In [13]:
UPJ = ("universitas","pembangunan","Jaya")
print(UPJ)

('universitas', 'pembangunan', 'Jaya')


In [14]:
nested_tuple = (100,(200,400,600),300,(400,800))
nested_tuple

(100, (200, 400, 600), 300, (400, 800))

In [15]:
nested_tuple [0]

100

In [16]:
nested_tuple [1]

(200, 400, 600)

In [17]:
nested_tuple [2]

300

In [18]:
nested_tuple [3]

(400, 800)

In [19]:
bin_colors = {"manual_color":"Yellow", "approved_color":"Green","refused_color":"Red"}
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [20]:
bin_colors.get('manual_color')

'Yellow'

In [21]:
bin_colors['approved_color']

'Green'

In [22]:
bin_colors['approved_color']='Purple'
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}


In [23]:
biodata ={"Nama":"Rifqi Muhammad","NIM":2020071014,"Prodi":"Informatika","Universitas":"UPJ"}
print(biodata)

{'Nama': 'Rifqi Muhammad', 'NIM': 2020071014, 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


In [24]:
biodata.get('Nama')

'Rifqi Muhammad'

In [25]:
biodata['Prodi']

'Informatika'

In [26]:
Green = {'Grass','Leaves'}
print(Green)

{'Leaves', 'Grass'}


In [27]:
Green = {'Grass','Leaves','Leaves','Grass'}
print(Green)

{'Leaves', 'Grass'}


In [28]:
yellow = {'dandelions', 'leaves', 'fire hydrant'}
red = {'rose','blood','leaves','fire hydrant' }

yellow|red

{'blood', 'dandelions', 'fire hydrant', 'leaves', 'rose'}

In [29]:
yellow&red

{'fire hydrant', 'leaves'}

In [34]:
import pandas as pd
df = pd.DataFrame([['1','Fares',32,True],['2','Elena',23,False],['3','Steven',40,True]])

In [35]:
print(df)

   0       1   2      3
0  1   Fares  32   True
1  2   Elena  23  False
2  3  Steven  40   True


In [36]:
df

0       1   2      3
0  1   Fares  32   True
1  2   Elena  23  False
2  3  Steven  40   True

In [37]:
df[['name','age']]

KeyError: "None of [Index(['name', 'age'], dtype='object')] are in the [columns]"

In [38]:
df.iloc[:,3]

0     True
1    False
2     True
Name: 3, dtype: bool

In [39]:
df.iloc[1:3,:]

0       1   2      3
1  2   Elena  23  False
2  3  Steven  40   True

In [40]:
df[df.age>30]

AttributeError: 'DataFrame' object has no attribute 'age'

In [41]:
df[(df.age<35)&(df.decision==True)]

AttributeError: 'DataFrame' object has no attribute 'age'

In [42]:
mhs=pd.DataFrame([['Informatika',50,30,20],['Sistem Informasi',55,30,25],['Teknik Sipil', 40,30,10]])

In [43]:
import numpy as np
myMatrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [44]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [45]:
Matrix = np.array([[100, 200, 300], [700, 600, 500], [900, 1000, 800]])
print(Matrix)

[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]


In [46]:
class Stack:
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def push(self, item):
        self.items.append(item)
    def pop(self):
        return self.items.pop()
    def peek(self):
        return self.items[len(self.items)-1]
    def size(self):
        return len(self.items)

In [47]:
stack = Stack()
stack.push('Red')
stack.push('Green')
stack.push('Blue')
stack.push('Yellow')

In [48]:
print(stack.pop())

Yellow


In [49]:
print(stack.isEmpty())

False


In [50]:
class Queue(object):
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def enqueue(self, item):
        self.items.insert(0,item)
    def dequeue(self):
        return self.items.pop()
    def size(self):
        return len(self.items)

In [51]:
queue =  Queue()
queue.enqueue('Red')
queue.enqueue('Green')
queue.enqueue('Blue')
queue.enqueue('Yellow')
print(queue.size())

4


In [52]:
print(queue.dequeue())

Red


In [53]:
print(queue.dequeue())

Green
